### ISSUE TITLE
Unable to find type [System.Net.IPNetwork]

### ISSUE THREAD

**Issue by dani3lh3pe** [eosfor/ipmgmt#1]
Hi @eosfor,
what you did here looks quite amazing for me! I was looking for a PowerShell based tool to calculate free ip address ranges for a while and your scripts and blog post look exactly like a pretty solution for me! So thanks so much for sharing at this point.

Why I'm texting you is that I have trouble to execute the script. 
When I just execute your test file "ipmgmt.Tests.ps1" and even own commands with own parameter values, I get the following error:

````powershell
Describing A simple test for Get-VLSMBreakdown
 [-] Passes a simple test for Get-VLSMBreakdown 53ms
   RuntimeException: Unable to find type [System.Net.IPNetwork].
   at <ScriptBlock>, <No file>: line 14
Describing A simple test for Get-IPRanges
 [-] Passes a simple test for Get-IPRanges 39ms
   RuntimeException: Unable to find type [System.Net.IPNetwork].
   at <ScriptBlock>, <No file>: line 20
````

It looks like that [System.Net.IPNetwork] cannot be loaded. I tried to figure out whats wrong here, but I was not able to.
May you have any idea whats the problem here?

Thank you very much!
Best
Daniel

**Comment by dani3lh3pe** [comment]
Hi @eosfor,
solved my problem. The problem was that I downloaded Package IPNetwork2 and copied the dll from "netcoreapp3.1" folder (so from .net core folder) instead of .net standard folder. With .net core I was not able to get this up and running, but with .net standard IPNetwork dll it works like a charm.

Again, thank you so much for sharing! Really appreciate your work!

**Comment by eosfor** [comment]
Hello @dani3lheidemann, I was under impression that everything needed is in this repo. the bin folder contains the needed dll. On the other hand, the module is published to the [powershell gallery](https://www.powershellgallery.com/packages/ipmgmt/0.1.5) and should have all the files right away. I think. 

How did you install it? I wonder if PowerShell gallery one does not work as expected. in this case, I should go and fix it.

**Comment by dani3lh3pe** [comment]
Hi @eosfor,
thanks for sharing the PowerShell Gallery Link. Didn't know you uploaded this as a module (may I missed it).
I just downloaded the ZIP right from here, but I'm not 100% sure, if I did everything correct.

However, I'll test the ipmgmt module and will let you know if everything's working.
Thank you!

**Comment by dani3lheidemann** [comment]
Hi @eosfor,
your PowerShell module is working like a charm, except when I want to deploy a VNET and only one Subnet from the same size (e.g., both are /24. But size does not matter). In this case, Get-VLSMBreakdown function does not find any available ranges for the subnet.

Are you able to reproduce it?
And in case you have the same problem – would you be so kind as to update the module? 
If you need any help, just drop a line!

Thank you!

**Comment by eosfor** [comment]
@dani3lheidemann, I've updated the code and published the new package version. you can try the new one, hope it works for you

**Comment by dani3lh3pe** [comment]
Hi @eosfor,
funny, I had the same idea to update your module. I initiated a pull request on the changes I made. Hope you find it helpful.
Reach out if you have any questions!
Thanks!

**Comment by eosfor** [comment]
Hopefully, I did everything right when resolving conflicts 😄 . If so - there should be a new package on the PowerShell gallery. You can check if everything is as expected

**Comment by eosfor** [comment]
it would be great if you could add a few tests for a new feature
